spring.application.name=CRMSecurity

server.port=8082

spring.datasource.url = jdbc:mysql://127.0.0.1/crm_db?useSSL=false
spring.datasource.username=root
spring.datasource.password=aman
server.servlet.context-path=/CRM-Security

#hibernate
spring.jpa.properties.hibernate.show_sql: true
